// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEbx4RJKCUlm7PR8ielmgFE-y8GzPZ7pQ',
    appId: '1:790718634349:web:9cd22bcd8d577931bc6264',
    messagingSenderId: '790718634349',
    projectId: 'duolingo2-cba7e',
    authDomain: 'duolingo2-cba7e.firebaseapp.com',
    storageBucket: 'duolingo2-cba7e.appspot.com',
    measurementId: 'G-7K9Y92YCJJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwQcRhssh5Etb25NKFERPZsnHc0qaTxm4',
    appId: '1:790718634349:android:8c154a716691dfa6bc6264',
    messagingSenderId: '790718634349',
    projectId: 'duolingo2-cba7e',
    storageBucket: 'duolingo2-cba7e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsEbm7L1-iwGvFWMPHZ1UbkDQHUvPMZnY',
    appId: '1:790718634349:ios:65b191b39d84c4cabc6264',
    messagingSenderId: '790718634349',
    projectId: 'duolingo2-cba7e',
    storageBucket: 'duolingo2-cba7e.appspot.com',
    iosBundleId: 'com.example.gamestellar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsEbm7L1-iwGvFWMPHZ1UbkDQHUvPMZnY',
    appId: '1:790718634349:ios:320f125842b5f3f2bc6264',
    messagingSenderId: '790718634349',
    projectId: 'duolingo2-cba7e',
    storageBucket: 'duolingo2-cba7e.appspot.com',
    iosBundleId: 'com.example.gamestellar.RunnerTests',
  );
}


